from pylab import *
nx=  256; ny=128; npm=  12
#nx=  128; ny=80; npm=  12
v1=zeros([ny,nx])
v2=zeros([ny,nx])
s11=zeros([ny,nx])
s22=zeros([ny,nx])
s12=zeros([ny,nx])
strini=zeros([ny,nx])
mu=zeros([ny,nx])
muu=zeros([ny,nx])
lam=zeros([ny,nx])
rho=zeros([ny,nx])
ro1=zeros([ny,nx])
ro2=zeros([ny,nx])
peak_12=zeros(nx)
strini=zeros(nx)
rdis=zeros(nx)
slip=zeros(nx)
broken=zeros(nx)
itim=zeros(nx)
fault=zeros(ny)
